### ISSUE TITLE
RepTrack

### ISSUE THREAD

**Issue by kellub** [anickle060193/ideas#1]
This idea is for a mobile app that tracks workouts. More specifically, this app is intended to track velocities and metrics of reps. The original plan was to use a Garmin device that supports logging of accelerometer data in accordance with the mobile app to improve the user experience. 
More specifically, a user would create a workout (consisting of individual exercises with specified # of sets with specified # of reps per set at specified weight(s)). Once the workout was created, the user would select an exercise to perform and then select a set. Once the set was selected, the mobile app would prompt the user to record set data on their Garmin watch (Garmin watch interface will be explained separately). Once the set has finished being recorded on the watch, the user could see various data about their set (min/max/avg velocity, a canvas element that would display the path of their wrist through the movement(s) using the accelerometer positioning, and the user could save notes about the particular set). The user would then go back to the exercise page and complete the next set and repeat.

Here is a picture of my rough ideas for the app, it's not fully fleshed out, but general screen design is there:
![android_app](https://user-images.githubusercontent.com/16668399/37188306-0af76874-2314-11e8-9c06-569d5d21ea56.jpg)

As for the Garmin watch app component of this, the idea is that the user will have a connection to a mobile phone (via connectIQ) and be prompted by the mobile app to record a set's data (or the entire workout could be sent to the watch, but that may be a future improvement). Once the user selects a set to complete on their phone, the watch will receive data from the phone about the set (exercise name, weight, # of reps). The user will then be prompted (on the watch) to grip the bar (with their watch hand) and then select 'record'. The watch would then begin tracking accelerometer data until the user pressed 'Stop'. At that point, the raw accelerometer data could be sent to the phone where it would be processed to calculate the min/max/avg velocities. That calculated data would be sent back to the watch and displayed for the user. The app would then wait for the next set prompt from the mobile device and repeat all of the above.

![watch_1](https://user-images.githubusercontent.com/16668399/37188307-0b0a0b82-2314-11e8-8033-604db74af634.jpg)
![watch_2](https://user-images.githubusercontent.com/16668399/37188308-0b2197d4-2314-11e8-880d-55eb4c9c325d.jpg)

**Comment by kellub** [comment]
Here is the link to my initial attempt at this (which I quickly lost steam on) https://github.com/kellub/repTrackAndroid. I'm not sure how useful it would be to look through since I didn't get very far, but here it is.

**Comment by anickle060193** [comment]
Created https://github.com/anickle060193/rep_track
